#!/usr/bin/env python3
import rospy
from morai_msgs.msg import GPSMessage
import pandas as pd
import datetime
import utm

df = pd.DataFrame(columns = ['seq', 'llatitude', 'longitude', 'llatitude_utm', 'longitude_utm'])

save_time = datetime.datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
csv_name = save_time + '.csv'

def gps_callback(msg):
    seq: int = msg.header.seq
    latitude: float = msg.latitude
    longitude: float = msg.longitude
    rospy.loginfo("seq: {}, latitude: {}, longitude {}".format(seq, latitude, longitude))

    utm_gps = utm.from_latlon(latitude, longitude)
    
    llatitude_utm: float = utm_gps[0]
    longitude_utm: float = utm_gps[1]

    df.loc[len(df)] = [seq, latitude, longitude, llatitude_utm, longitude_utm]

    df.to_csv(csv_name, index = False)

if __name__ == '__main__':
    rospy.init_node('gps_data')
    sub_gps = rospy.Subscriber('/gps', GPSMessage, gps_callback)
    rospy.spin()
    print("\n",csv_name, "save")